version: '3'

services:
  mysql:
    image: mysql:5.6
    ports:
      - "3308:3306"
    volumes:
      - ./database-volume:/var/lib/myslq
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app_development
  app:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    depends_on:
        - mysql
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
